853 fedramp platform changelog
GSA/fedramp-gov pull request #860
Opened 2024-11-06 03:19 UTC by aj-stein-gsa

This is a draft of the current changelog page with status, description, and milestone timelines. Once review, approved, and merged. This issue closes #853.

2024-11-06 04:12 UTC, david-waltermire commented on pages/updates/platform.md
> +- FY25 Q4 - FY26 - **Later** -  FedRAMP will provide live and on-demand training and start deploying the Platform.
```suggestion
- FY25 Q4 thru  FY26 - **Later** -  FedRAMP will provide live and on-demand training and start deploying the Platform.
```

2024-11-06 04:12 UTC, david-waltermire commented on pages/updates/platform.md
> +- FY24 Q4 - FY25 Q1 - **In Progress** - FedRAMP began ongoing human-centered design sessions.
```suggestion
- FY24 Q4 thru FY25 Q1 - **In Progress** - FedRAMP began ongoing human-centered design sessions.
```

2024-11-07 20:41 UTC, Marcia-Simms submitted a review, later dismissed

2024-11-07 20:59 UTC, Marcia-Simms requested changes

2024-11-07 20:59 UTC, Marcia-Simms commented on pages/updates/platform.md
> +The Platform is for FedRAMP, agency, cloud service providers, and third party assessor staff to collaborate on digital authorization packages and continuous monitoring data in a unified portal. Movin
```suggestion
The Platform is for FedRAMP, agencies, cloud service providers, and third party assessment organization (3PAO) staff to collaborate on digital authorization packages and continuous monitoring data in a unified portal. Moving forward, FedRAMP will facilitate interactions with these stakeholders in the portal using the Platform’s web interface or automated workflows via application programming interfaces (APIs). This approach will make authorizations easier, expand continuous monitoring capabilities, enhance communication between stakeholders, and facilitate tracking and publishing metrics transparently.
```

2024-11-07 20:59 UTC, Marcia-Simms commented on pages/updates/platform.md
> +- FY24 Q4 - **FY25 Q2** - In Progress - FedRAMP began ongoing human-centered design sessions.
```suggestion
- FY24 Q4 - **FY25 Q2** - In Progress - FedRAMP launched ongoing human-centered design sessions.
```

2024-11-07 20:59 UTC, Marcia-Simms commented on pages/updates/platform.md
> +- FY25 Q2 - **Next** - FedRAMP will conduct a pilot of the continuous monitoring processes via the Platform with synthetic data.
```suggestion
- FY25 Q2 - **Next** - FedRAMP will conduct a pilot of the continuous monitoring processes in the Platform with synthetic data.
```

2024-11-07 20:59 UTC, Marcia-Simms commented on pages/updates/platform.md
> +- FY25 Q3 - **Later** - FedRAMP obtains a GSA Authority to Operate (ATO) and develops APIs with select agencies. Once completed, FedRAMP will deploy the platform.
```suggestion
- FY25 Q3 - **Later** - FedRAMP obtains a GSA Authority to Operate (ATO) and develops APIs with select agencies. Once completed, FedRAMP will deploy the Platform.
```

2024-11-07 20:59 UTC, Marcia-Simms commented on pages/updates/platform.md
> +FedRAMP is actively working with our stakeholders, using a human-centered design approach, to incrementally design, test, and deploy the FedRAMP Platform. You can learn more about the journey, our pr
```suggestion
FedRAMP is actively working with our stakeholders, using a human-centered design approach, to incrementally design, test, and deploy the FedRAMP Platform. You can learn more about the journey, our progress, and key milestones below.
```

2024-11-07 21:02 UTC, Marcia-Simms approved these changes

2024-11-07 22:16 UTC, pete-gov approved these changes
I shed a tiny tear of joy.

2024-11-07 22:20 UTC, merged